services:
  server:
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4"]
  
  db:
    env_file:
      - .env.prod
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5436:5432"

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["alembic", "upgrade", "head"]
    restart: "no"


volumes:
  dbdata_prod: