"""replace target_id with reference_id in notifications

Revision ID: 0f9a664f6725
Revises: cdd1e1318ae3
Create Date: 2026-08-03 14:23:24.478866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f9a664f6725'
down_revision: Union[str, Sequence[str], None] = 'cdd1e1318ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('reference_id', sa.UUID(), nullable=True))
    op.drop_column('notifications', 'target_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('target_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_column('notifications', 'reference_id')
    # ### end Alembic commands ###
