"""increase length of bank account_no field

Revision ID: 3a2f403578c6
Revises: 5a2bba5302d2
Create Date: 2026-02-12 22:02:05.938158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a2f403578c6'
down_revision: Union[str, Sequence[str], None] = '5a2bba5302d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_details', 'account_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=127),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_details', 'account_number',
               existing_type=sa.String(length=127),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
