"""set payout upload status as non-nullible

Revision ID: 3f6806d25df6
Revises: 5b11326a52b6
Create Date: 2026-03-19 20:09:24.132731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f6806d25df6'
down_revision: Union[str, Sequence[str], None] = '5b11326a52b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payouts', 'upload_status',
               existing_type=postgresql.ENUM('pending', 'failed', 'completed', name='uploadstatusenum'),
               nullable=False)
    op.alter_column('transactions', 'status',
               existing_type=postgresql.ENUM('approved', 'pending', 'active', name='transactionstatusenum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'status',
               existing_type=postgresql.ENUM('approved', 'pending', 'active', name='transactionstatusenum'),
               nullable=True)
    op.alter_column('payouts', 'upload_status',
               existing_type=postgresql.ENUM('pending', 'failed', 'completed', name='uploadstatusenum'),
               nullable=True)
    # ### end Alembic commands ###
