"""add rank to affilate tiers

Revision ID: 405d42d07b16
Revises: 9aeb7a10536a
Create Date: 2026-02-16 05:13:26.235043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '405d42d07b16'
down_revision: Union[str, Sequence[str], None] = '9aeb7a10536a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('affiliate_commissions_transaction_id_fkey'), 'affiliate_commissions', type_='foreignkey')
    op.create_foreign_key(None, 'affiliate_commissions', 'transactions', ['transaction_id'], ['id'])
    op.add_column('affiliate_tiers', sa.Column('rank', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'affiliate_tiers', ['rank'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'affiliate_tiers', type_='unique')
    op.drop_column('affiliate_tiers', 'rank')
    op.drop_constraint(None, 'affiliate_commissions', type_='foreignkey')
    op.create_foreign_key(op.f('affiliate_commissions_transaction_id_fkey'), 'affiliate_commissions', 'transactions', ['transaction_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
