"""set tier max volume as nullable

Revision ID: 434c278f47ca
Revises: accde9395427
Create Date: 2026-02-12 05:22:45.174703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '434c278f47ca'
down_revision: Union[str, Sequence[str], None] = 'accde9395427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tier_volume_bands', 'max_volume',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tier_volume_bands', 'max_volume',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False)
    # ### end Alembic commands ###
