"""drop and recreate transaction crypto_pair column

Revision ID: 440e20a4c84c
Revises: db6138eb5f7c
Create Date: 2026-01-27 07:16:19.001323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '440e20a4c84c'
down_revision: Union[str, Sequence[str], None] = 'db6138eb5f7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'crypto_pair')
    op.add_column('transactions', sa.Column('crypto_pair', postgresql.ENUM('NGN-USDT', 'USDT-NGN', 'BTC-NGN', 'NGN-BTC', 'ETH-NGN', 'NGN-ETH', name='cryptopairenum'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'crypto_pair')
    op.add_column('transactions', sa.Column('crypto_pair', postgresql.ENUM('NGN-USDT', 'USDT-NGN', 'BTC-NGN', 'NGN-BTC', 'ETH-NGN', 'NGN-ETH', name='cryptopairenum'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
