"""add status field to rate change log table

Revision ID: 4441132d04cc
Revises: 9c640f169e19
Create Date: 2026-07-16 19:05:56.067990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4441132d04cc'
down_revision: Union[str, Sequence[str], None] = '9c640f169e19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rate_change_logs', sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='ratesapprovalstatusenum'), nullable=False))
    op.create_index(op.f('ix_rate_change_logs_status'), 'rate_change_logs', ['status'], unique=False)
    op.create_unique_constraint(None, 'rate_change_logs', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rate_change_logs', type_='unique')
    op.drop_index(op.f('ix_rate_change_logs_status'), table_name='rate_change_logs')
    op.drop_column('rate_change_logs', 'status')
    # ### end Alembic commands ###
