"""add target id to rate proposal model

Revision ID: 50d6f34909a0
Revises: 28585768369c
Create Date: 2026-07-15 10:41:58.852543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50d6f34909a0'
down_revision: Union[str, Sequence[str], None] = '28585768369c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rate_approval_requests', sa.Column('target_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_rate_approval_requests_target_id'), 'rate_approval_requests', ['target_id'], unique=False)
    op.create_unique_constraint(None, 'rate_approval_requests', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rate_approval_requests', type_='unique')
    op.drop_index(op.f('ix_rate_approval_requests_target_id'), table_name='rate_approval_requests')
    op.drop_column('rate_approval_requests', 'target_id')
    # ### end Alembic commands ###
