"""remove currency field from transactions table

Revision ID: 56611bf99170
Revises: a66c767cf63d
Create Date: 2026-01-11 13:04:33.785359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56611bf99170'
down_revision: Union[str, Sequence[str], None] = 'a66c767cf63d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
