"""remove pay_ref field and increase length of payment_ref

Revision ID: 598d44e591bb
Revises: b3715906f7af
Create Date: 2026-02-13 09:25:09.187771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '598d44e591bb'
down_revision: Union[str, Sequence[str], None] = 'b3715906f7af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'affiliate_commissions', ['id'])
    op.create_unique_constraint(None, 'affiliate_monthly_volume', ['id'])
    op.create_unique_constraint(None, 'affiliate_tiers', ['id'])
    op.create_unique_constraint(None, 'affiliate_visits', ['id'])
    op.create_unique_constraint(None, 'affiliates', ['id'])
    op.create_unique_constraint(None, 'bank_details', ['id'])
    op.create_unique_constraint(None, 'customers', ['id'])
    op.create_unique_constraint(None, 'erp_users', ['id'])
    op.create_unique_constraint(None, 'mock_customers', ['id'])
    op.create_unique_constraint(None, 'notifications', ['id'])
    op.alter_column('payouts', 'payment_ref',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_constraint(op.f('payouts_pay_ref_key'), 'payouts', type_='unique')
    op.create_unique_constraint(None, 'payouts', ['id'])
    op.drop_column('payouts', 'pay_ref')
    op.create_unique_constraint(None, 'permissions', ['id'])
    op.create_unique_constraint(None, 'roles', ['id'])
    op.create_unique_constraint(None, 'service_types', ['id'])
    op.create_unique_constraint(None, 'tier_volume_bands', ['id'])
    op.create_unique_constraint(None, 'transaction_types', ['id'])
    op.create_unique_constraint(None, 'transactions', ['txn_id'])
    op.create_unique_constraint(None, 'transactions', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_constraint(None, 'transaction_types', type_='unique')
    op.drop_constraint(None, 'tier_volume_bands', type_='unique')
    op.drop_constraint(None, 'service_types', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_constraint(None, 'permissions', type_='unique')
    op.add_column('payouts', sa.Column('pay_ref', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'payouts', type_='unique')
    op.create_unique_constraint(op.f('payouts_pay_ref_key'), 'payouts', ['pay_ref'], postgresql_nulls_not_distinct=False)
    op.alter_column('payouts', 'payment_ref',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    op.drop_constraint(None, 'notifications', type_='unique')
    op.drop_constraint(None, 'mock_customers', type_='unique')
    op.drop_constraint(None, 'erp_users', type_='unique')
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_constraint(None, 'bank_details', type_='unique')
    op.drop_constraint(None, 'affiliates', type_='unique')
    op.drop_constraint(None, 'affiliate_visits', type_='unique')
    op.drop_constraint(None, 'affiliate_tiers', type_='unique')
    op.drop_constraint(None, 'affiliate_monthly_volume', type_='unique')
    op.drop_constraint(None, 'affiliate_commissions', type_='unique')
    # ### end Alembic commands ###
