"""update mock customer schema

Revision ID: 59ab3fa39956
Revises: 22d0602c7081
Create Date: 2025-12-03 09:44:13.751691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59ab3fa39956'
down_revision: Union[str, Sequence[str], None] = '22d0602c7081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mock_customers', sa.Column('first_name', sa.String(length=200), nullable=False))
    op.add_column('mock_customers', sa.Column('last_name', sa.String(length=200), nullable=False))
    op.add_column('mock_customers', sa.Column('email', sa.String(length=120), nullable=False))
    op.drop_column('mock_customers', 'transaction_type')
    op.drop_column('mock_customers', 'full_name')
    op.drop_column('mock_customers', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mock_customers', sa.Column('amount', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('mock_customers', sa.Column('full_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('mock_customers', sa.Column('transaction_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('mock_customers', 'email')
    op.drop_column('mock_customers', 'last_name')
    op.drop_column('mock_customers', 'first_name')
    # ### end Alembic commands ###
