"""add attachment and upload status field to payouts model, reintroduce transaction status

Revision ID: 5b11326a52b6
Revises: 405d42d07b16
Create Date: 2026-03-17 18:29:59.194307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b11326a52b6'
down_revision: Union[str, Sequence[str], None] = '405d42d07b16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payouts', sa.Column('upload_status', sa.Enum('pending', 'failed', 'completed', name='uploadstatusenum'), nullable=True))
    op.add_column('payouts', sa.Column('note', sa.String(length=255), nullable=True))
    op.add_column('payouts', sa.Column('attachment_url', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('status', sa.Enum('approved', 'pending', 'upload_pending', 'active', name='transactionstatusenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'status')
    op.drop_column('payouts', 'attachment_url')
    op.drop_column('payouts', 'note')
    op.drop_column('payouts', 'upload_status')
    # ### end Alembic commands ###
