"""rename attachment field and add upload status field

Revision ID: 6021fd2d5f92
Revises: 757d0d875273
Create Date: 2026-01-07 09:26:06.386987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6021fd2d5f92'
down_revision: Union[str, Sequence[str], None] = '757d0d875273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


upload_status_enum = sa.Enum('pending', 'failed', 'completed', name='uploadstatusenum')

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create enum types first
    upload_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('transactions', sa.Column('upload_status', sa.Enum('pending', 'failed', 'completed', name='uploadstatusenum'), nullable=False))
    op.add_column('transactions', sa.Column('attachment_url', sa.String(), nullable=True))
    op.drop_column('transactions', 'attatchment_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('attatchment_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('transactions', 'attachment_url')
    op.drop_column('transactions', 'upload_status')

    # Drop enum types last
    upload_status_enum.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
