"""convert role_permission association table to model

Revision ID: 688f1e256c68
Revises: e8dd9e7437e7
Create Date: 2026-01-31 16:16:47.795077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '688f1e256c68'
down_revision: Union[str, Sequence[str], None] = 'e8dd9e7437e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_permissions', sa.Column('is_allowed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role_permissions', 'is_allowed')
    # ### end Alembic commands ###
