"""removed unneeded fields in customer model

Revision ID: 6c4c65c29e43
Revises: 86e1c781b2d3
Create Date: 2025-12-30 19:40:43.114727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c4c65c29e43'
down_revision: Union[str, Sequence[str], None] = '86e1c781b2d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_signed_up'), table_name='customers')
    op.drop_column('customers', 'commission')
    op.drop_column('customers', 'hashed_password')
    op.drop_column('customers', 'signed_up')
    op.drop_column('customers', 'signup_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('signup_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('signed_up', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('commission', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0.0'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_customers_signed_up'), 'customers', ['signed_up'], unique=False)
    # ### end Alembic commands ###
