"""transactions update

Revision ID: 757d0d875273
Revises: 65deda1c8dc6
Create Date: 2026-01-05 08:08:25.467353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '757d0d875273'
down_revision: Union[str, Sequence[str], None] = '65deda1c8dc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


service_type_enum = sa.Enum(
    'crypto',
    'gift_card',
    'bill_payments',
    name='servicetypeenum'
)

crypto_pair_enum = sa.Enum(
    'NGN_USDT',
    'USDT_NGN',
    name='cryptopairenum'
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create enum types first
    service_type_enum.create(op.get_bind(), checkfirst=True)
    crypto_pair_enum.create(op.get_bind(), checkfirst=True)

    op.drop_column('transactions', 'commission_amount')

    op.add_column('transactions', sa.Column('commission_amount', sa.DECIMAL(precision=12, scale=2), sa.Computed("amount_in * commission_rate / 100", persisted=True), nullable=False))

    op.add_column('transactions', sa.Column('service_type', sa.Enum('crypto', 'gift_card', 'bill_payments', name='servicetypeenum'), nullable=False))
    op.add_column('transactions', sa.Column('currency_in', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('currency_out', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('crypto_pair', sa.Enum('NGN_USDT', 'USDT_NGN', name='cryptopairenum'), nullable=True))
    op.add_column('transactions', sa.Column('gift_card_type', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('gift_card_code', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('attatchment_url', sa.String(), nullable=True))
    op.alter_column('transactions', 'amount_in',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.drop_column('transactions', 'transaction_amount')
    op.drop_column('transactions', 'transaction_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('transactions', 'commission_amount')
    op.add_column('transactions', sa.Column('commission_amount', sa.DECIMAL(precision=12, scale=2), sa.Computed("transaction_amount * commission_rate / 100", persisted=True), nullable=False))

    op.add_column('transactions', sa.Column('transaction_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('transaction_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.alter_column('transactions', 'amount_in',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.drop_column('transactions', 'attatchment_url')
    op.drop_column('transactions', 'gift_card_code')
    op.drop_column('transactions', 'quantity')
    op.drop_column('transactions', 'currency')
    op.drop_column('transactions', 'gift_card_type')
    op.drop_column('transactions', 'crypto_pair')
    op.drop_column('transactions', 'currency_out')
    op.drop_column('transactions', 'currency_in')
    op.drop_column('transactions', 'service_type')

    # Drop enum types last
    crypto_pair_enum.drop(op.get_bind(), checkfirst=True)
    service_type_enum.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
