"""update payout status enum

Revision ID: 79745dbdd81e
Revises: ead32e511a28
Create Date: 2025-11-28 01:46:14.852953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79745dbdd81e'
down_revision: Union[str, Sequence[str], None] = 'ead32e511a28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE payoutstatusenum ADD VALUE IF NOT EXISTS 'rejected'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
