"""add transaction updates and new type/service models

Revision ID: 86e1c781b2d3
Revises: 59ab3fa39956
Create Date: 2025-12-16 08:48:31.343682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e1c781b2d3'
down_revision: Union[str, Sequence[str], None] = '59ab3fa39956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    service_type_enum = sa.Enum(
        'crypto', 
        'gift_card', 
        'bill_payments', 
        name='servicetypeenum'
    )

    op.create_table(
        'service_types',
        sa.Column('name', service_type_enum, nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_service_types_name'), 'service_types', ['name'], unique=False)
    op.create_table(
        'transaction_types',
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('service_type_id', sa.UUID(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_transaction_types_name'), 'transaction_types', ['name'], unique=False)
    op.create_index(op.f('ix_transaction_types_service_type_id'), 'transaction_types', ['service_type_id'], unique=False)
    op.add_column('transactions', sa.Column('amount_in', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('amount_out', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('vendor_rate', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('xbanka_rate', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('margin', sa.Numeric(precision=12, scale=2), sa.Computed('xbanka_rate - vendor_rate', persisted=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'margin')
    op.drop_column('transactions', 'xbanka_rate')
    op.drop_column('transactions', 'vendor_rate')
    op.drop_column('transactions', 'amount_out')
    op.drop_column('transactions', 'amount_in')
    op.drop_index(op.f('ix_transaction_types_service_type_id'), table_name='transaction_types')
    op.drop_index(op.f('ix_transaction_types_name'), table_name='transaction_types')
    op.drop_table('transaction_types')
    op.drop_index(op.f('ix_service_types_name'), table_name='service_types')
    op.drop_table('service_types')
    sa.Enum(name='servicetypeenum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
