"""add txn id field to transactions model

Revision ID: 9188db843495
Revises: 56611bf99170
Create Date: 2026-01-16 09:27:42.247345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9188db843495'
down_revision: Union[str, Sequence[str], None] = '56611bf99170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('txn_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'txn_id')
    # ### end Alembic commands ###
