"""add relationship between affiliates and notifications

Revision ID: 94537dae271a
Revises: 79745dbdd81e
Create Date: 2025-11-29 13:30:38.945251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94537dae271a'
down_revision: Union[str, Sequence[str], None] = '79745dbdd81e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('affiliate_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_notifications_affiliate_id'), 'notifications', ['affiliate_id'], unique=False)
    op.create_foreign_key('fx_notifications_affiliate', 'notifications', 'affiliates', ['affiliate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fx_notifications_affiliate', 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_affiliate_id'), table_name='notifications')
    op.drop_column('notifications', 'affiliate_id')
    # ### end Alembic commands ###
