"""add transaction commission cascade delete

Revision ID: 9aeb7a10536a
Revises: 598d44e591bb
Create Date: 2026-02-15 15:21:49.446917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aeb7a10536a'
down_revision: Union[str, Sequence[str], None] = '598d44e591bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'affiliate_commissions_transaction_id_fkey',  # existing FK name
        'affiliate_commissions',
        type_='foreignkey'
    )
    # Re-create it with ON DELETE CASCADE
    op.create_foreign_key(
        'affiliate_commissions_transaction_id_fkey',
        'affiliate_commissions',
        'transactions',
        ['transaction_id'],
        ['id'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'affiliate_commissions_transaction_id_fkey',
        'affiliate_commissions',
        type_='foreignkey'
    )
    # Re-create the original FK without ON DELETE CASCADE
    op.create_foreign_key(
        'affiliate_commissions_transaction_id_fkey',
        'affiliate_commissions',
        'transactions',
        ['transaction_id'],
        ['id']
    )
    # ### end Alembic commands ###
