"""add rate changelog table

Revision ID: 9c640f169e19
Revises: 50d6f34909a0
Create Date: 2026-07-16 17:38:22.020718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c640f169e19'
down_revision: Union[str, Sequence[str], None] = '50d6f34909a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

approval_type = postgresql.ENUM(
    "ASSET_UPDATE",
    "SEGMENT_UPDATE",
    "SEGMENT_ASSIGNMENT",
    name="rateapprovalrequesttypeenum",
    create_type=False,
)

approval_type.create(op.get_bind(), checkfirst=True)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_change_logs',
    sa.Column('type', approval_type, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('performed_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['performed_by_id'], ['erp_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_rate_change_logs_performed_by_id'), 'rate_change_logs', ['performed_by_id'], unique=False)
    op.create_index(op.f('ix_rate_change_logs_target_id'), 'rate_change_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_rate_change_logs_type'), 'rate_change_logs', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_change_logs_type'), table_name='rate_change_logs')
    op.drop_index(op.f('ix_rate_change_logs_target_id'), table_name='rate_change_logs')
    op.drop_index(op.f('ix_rate_change_logs_performed_by_id'), table_name='rate_change_logs')
    op.drop_table('rate_change_logs')
    # ### end Alembic commands ###
