"""add additional fields to transactions - customer and xbanka account, vendor and giftcard code

Revision ID: a66c767cf63d
Revises: 6021fd2d5f92
Create Date: 2026-01-10 06:19:20.743176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a66c767cf63d'
down_revision: Union[str, Sequence[str], None] = '6021fd2d5f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('vendor', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('customer_account', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('xbanka_account', sa.String(), nullable=True))

    op.execute("ALTER TYPE cryptopairenum ADD VALUE IF NOT EXISTS 'BTC-NGN'")
    op.execute("ALTER TYPE cryptopairenum ADD VALUE IF NOT EXISTS 'NGN-BTC'")
    op.execute("ALTER TYPE cryptopairenum ADD VALUE IF NOT EXISTS 'ETH-NGN'")
    op.execute("ALTER TYPE cryptopairenum ADD VALUE IF NOT EXISTS 'NGN-ETH'")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'xbanka_account')
    op.drop_column('transactions', 'customer_account')
    op.drop_column('transactions', 'vendor')

    op.execute("DROP TYPE cryptopairenum")
    op.execute("ALTER TYPE cryptopairenum_new RENAME TO cryptopairenum")
    # ### end Alembic commands ###
