"""add new tables for commission tier structure

Revision ID: accde9395427
Revises: 688f1e256c68
Create Date: 2026-02-12 04:10:36.875842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'accde9395427'
down_revision: Union[str, Sequence[str], None] = '688f1e256c68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliate_tiers',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_restricted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tier_volume_bands',
    sa.Column('tier_name', sa.String(), nullable=False),
    sa.Column('tier_id', sa.UUID(), nullable=False),
    sa.Column('min_volume', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('max_volume', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tier_id'], ['affiliate_tiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tier_volume_bands_tier_id'), 'tier_volume_bands', ['tier_id'], unique=False)
    op.create_table('affiliate_monthly_volume',
    sa.Column('affiliate_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('total_volume', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_commission', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('affiliate_id', 'month', name='uix_affiliate_monthly_volume')
    )
    op.create_index(op.f('ix_affiliate_monthly_volume_affiliate_id'), 'affiliate_monthly_volume', ['affiliate_id'], unique=False)
    op.create_table('affiliate_commissions',
    sa.Column('affiliate_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('affiliate_id', 'transaction_id', name='uix_affiliate_transaction')
    )
    op.create_index(op.f('ix_affiliate_commissions_affiliate_id'), 'affiliate_commissions', ['affiliate_id'], unique=False)
    op.create_index(op.f('ix_affiliate_commissions_transaction_id'), 'affiliate_commissions', ['transaction_id'], unique=False)
    op.add_column('affiliates', sa.Column('current_tier_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_affiliates_current_tier_id'), 'affiliates', ['current_tier_id'], unique=False)
    op.create_foreign_key(None, 'affiliates', 'affiliate_tiers', ['current_tier_id'], ['id'])
    op.add_column('payouts', sa.Column('pay_ref', sa.String(), nullable=True, unique=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payouts', 'pay_ref')
    op.drop_index(op.f('ix_affiliates_current_tier_id'), table_name='affiliates')
    op.drop_column('affiliates', 'current_tier_id')
    op.drop_index(op.f('ix_affiliate_commissions_transaction_id'), table_name='affiliate_commissions')
    op.drop_index(op.f('ix_affiliate_commissions_affiliate_id'), table_name='affiliate_commissions')
    op.drop_table('affiliate_commissions')
    op.drop_index(op.f('ix_affiliate_monthly_volume_affiliate_id'), table_name='affiliate_monthly_volume')
    op.drop_table('affiliate_monthly_volume')
    op.drop_index(op.f('ix_tier_volume_bands_tier_id'), table_name='tier_volume_bands')
    op.drop_table('tier_volume_bands')
    op.drop_table('affiliate_tiers')
    # ### end Alembic commands ###
