"""add google_id field to Affiliate model

Revision ID: b055cf743085
Revises: d041a717b4c5
Create Date: 2026-03-30 12:35:52.763358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b055cf743085'
down_revision: Union[str, Sequence[str], None] = 'd041a717b4c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliates', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'affiliates', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'affiliates', type_='unique')
    op.drop_column('affiliates', 'google_id')
    # ### end Alembic commands ###
