"""drop affiliate bank and account_no fields

Revision ID: b3715906f7af
Revises: 3a2f403578c6
Create Date: 2026-02-12 22:15:33.706465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3715906f7af'
down_revision: Union[str, Sequence[str], None] = '3a2f403578c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_affiliates_bank'), table_name='affiliates')
    op.drop_column('affiliates', 'account_no')
    op.drop_column('affiliates', 'bank')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliates', sa.Column('bank', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('affiliates', sa.Column('account_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_affiliates_bank'), 'affiliates', ['bank'], unique=False)
    # ### end Alembic commands ###
