"""make phone no and password nullable to support google auth

Revision ID: b78d0f9c77e4
Revises: 3f6806d25df6
Create Date: 2026-03-29 18:17:43.965724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b78d0f9c77e4'
down_revision: Union[str, Sequence[str], None] = '3f6806d25df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliates', sa.Column('auth_provider', sa.Enum('email', 'google', name='authproviderenum'), nullable=True))
    op.alter_column('affiliates', 'phone_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('affiliates', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('affiliates', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('affiliates', 'phone_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('affiliates', 'auth_provider')
    # ### end Alembic commands ###
