"""add target id to notifications

Revision ID: cdd1e1318ae3
Revises: a1f3c9d7b2e4
Create Date: 2026-08-03 14:11:29.913511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdd1e1318ae3'
down_revision: Union[str, Sequence[str], None] = 'a1f3c9d7b2e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('target_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'target_id')
    # ### end Alembic commands ###
