"""add permission category field

Revision ID: cf95b569ec4d
Revises: 9b888d18a795
Create Date: 2026-01-22 08:03:41.376184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf95b569ec4d'
down_revision: Union[str, Sequence[str], None] = '9b888d18a795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('category', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_permissions_category'), 'permissions', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permissions_category'), table_name='permissions')
    op.drop_column('permissions', 'category')
    # ### end Alembic commands ###
