"""add non nullable constraint to auth_provider

Revision ID: d041a717b4c5
Revises: b78d0f9c77e4
Create Date: 2026-03-29 18:56:28.954944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd041a717b4c5'
down_revision: Union[str, Sequence[str], None] = 'b78d0f9c77e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('affiliates', 'auth_provider',
               existing_type=postgresql.ENUM('email', 'google', name='authproviderenum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('affiliates', 'auth_provider',
               existing_type=postgresql.ENUM('email', 'google', name='authproviderenum'),
               nullable=True)
    # ### end Alembic commands ###
