"""remove transaction status

Revision ID: e8dd9e7437e7
Revises: f7015fcd4cc0
Create Date: 2026-01-28 22:40:48.037631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8dd9e7437e7'
down_revision: Union[str, Sequence[str], None] = 'f7015fcd4cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('status', postgresql.ENUM('approved', 'pending', 'active', name='transactionstatusenum'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
