"""initial migration

Revision ID: ead32e511a28
Revises: 
Create Date: 2025-11-28 00:12:05.172760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ead32e511a28'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliates',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('phone_no', sa.String(length=50), nullable=False),
    sa.Column('bank', sa.String(length=50), nullable=False),
    sa.Column('account_no', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('ref_code', sa.String(length=50), nullable=False),
    sa.Column('custom_refcode', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_refcode'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('ref_code')
    )
    op.create_index(op.f('ix_affiliates_bank'), 'affiliates', ['bank'], unique=False)
    op.create_index(op.f('ix_affiliates_email'), 'affiliates', ['email'], unique=True)
    op.create_index(op.f('ix_affiliates_first_name'), 'affiliates', ['first_name'], unique=False)
    op.create_index(op.f('ix_affiliates_last_name'), 'affiliates', ['last_name'], unique=False)
    op.create_index(op.f('ix_affiliates_username'), 'affiliates', ['username'], unique=True)
    op.create_table('erp_users',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('customer_support', name='userroleenum'), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_erp_users_email'), 'erp_users', ['email'], unique=True)
    op.create_index(op.f('ix_erp_users_first_name'), 'erp_users', ['first_name'], unique=False)
    op.create_index(op.f('ix_erp_users_last_name'), 'erp_users', ['last_name'], unique=False)
    op.create_index(op.f('ix_erp_users_role'), 'erp_users', ['role'], unique=False)
    op.create_table('mock_customers',
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone_no', sa.String(length=50), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.String(length=50), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('message', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('system', 'whatsapp', name='notificationtypeenum'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('method', sa.Enum('bank_transfer', 'mobile_money', name='payoutmethodenum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_method'), 'notifications', ['method'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_table('customers',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_no', sa.String(length=50), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('signed_up', sa.Boolean(), nullable=False),
    sa.Column('signup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('converted', sa.Boolean(), nullable=False),
    sa.Column('conversion_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('commission', sa.DECIMAL(precision=12, scale=2), server_default=sa.text('0.0'), nullable=False),
    sa.Column('affiliate_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_customers_affiliate_id'), 'customers', ['affiliate_id'], unique=False)
    op.create_index(op.f('ix_customers_converted'), 'customers', ['converted'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_first_name'), 'customers', ['first_name'], unique=False)
    op.create_index(op.f('ix_customers_last_name'), 'customers', ['last_name'], unique=False)
    op.create_index(op.f('ix_customers_signed_up'), 'customers', ['signed_up'], unique=False)
    op.create_table('payouts',
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('paid', 'pending', 'failed', name='payoutstatusenum'), nullable=False),
    sa.Column('payment_ref', sa.String(length=120), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bank', sa.String(length=100), nullable=False),
    sa.Column('affiliate_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('payment_ref')
    )
    op.create_index(op.f('ix_payouts_affiliate_id'), 'payouts', ['affiliate_id'], unique=False)
    op.create_table('transactions',
    sa.Column('affiliate_source', sa.String(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('transaction_amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('commission_rate', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('commission_amount', sa.DECIMAL(precision=12, scale=2), sa.Computed('transaction_amount * commission_rate / 100', persisted=True), nullable=False),
    sa.Column('status', sa.Enum('approved', 'pending', 'active', name='transactionstatusenum'), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_transactions_customer_id'), 'transactions', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_customer_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_payouts_affiliate_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_customers_signed_up'), table_name='customers')
    op.drop_index(op.f('ix_customers_last_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_first_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_converted'), table_name='customers')
    op.drop_index(op.f('ix_customers_affiliate_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_method'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('mock_customers')
    op.drop_index(op.f('ix_erp_users_role'), table_name='erp_users')
    op.drop_index(op.f('ix_erp_users_last_name'), table_name='erp_users')
    op.drop_index(op.f('ix_erp_users_first_name'), table_name='erp_users')
    op.drop_index(op.f('ix_erp_users_email'), table_name='erp_users')
    op.drop_table('erp_users')
    op.drop_index(op.f('ix_affiliates_username'), table_name='affiliates')
    op.drop_index(op.f('ix_affiliates_last_name'), table_name='affiliates')
    op.drop_index(op.f('ix_affiliates_first_name'), table_name='affiliates')
    op.drop_index(op.f('ix_affiliates_email'), table_name='affiliates')
    op.drop_index(op.f('ix_affiliates_bank'), table_name='affiliates')
    op.drop_table('affiliates')
    # ### end Alembic commands ###
