"""add rates request table

Revision ID: efd4ed7c2996
Revises: 1b651c39abec
Create Date: 2026-06-29 13:51:00.972600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efd4ed7c2996'
down_revision: Union[str, Sequence[str], None] = '1b651c39abec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_approval_requests',
    sa.Column('type', sa.Enum('ASSET_UPDATE', 'SEGMENT_UPDATE', 'SEGMENT_ASSIGNMENT', name='rateapprovalrequesttypeenum'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='ratesapprovalstatusenum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['erp_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_rate_approval_requests_requested_by'), 'rate_approval_requests', ['requested_by'], unique=False)
    op.create_index(op.f('ix_rate_approval_requests_status'), 'rate_approval_requests', ['status'], unique=False)
    op.create_index(op.f('ix_rate_approval_requests_type'), 'rate_approval_requests', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_approval_requests_type'), table_name='rate_approval_requests')
    op.drop_index(op.f('ix_rate_approval_requests_status'), table_name='rate_approval_requests')
    op.drop_index(op.f('ix_rate_approval_requests_requested_by'), table_name='rate_approval_requests')
    op.drop_table('rate_approval_requests')
    # ### end Alembic commands ###
