"""create transaction crypto_pair column

Revision ID: f7015fcd4cc0
Revises: 54363a2efd43
Create Date: 2026-01-27 07:26:08.291187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.core.enums import CryptoPairEnum


# revision identifiers, used by Alembic.
revision: str = 'f7015fcd4cc0'
down_revision: Union[str, Sequence[str], None] = '54363a2efd43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

ENUM_NAME = 'cryptopairenum'

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # drop existing enum type
    op.execute(f"DROP TYPE IF EXISTS {ENUM_NAME}")

    # create enum type again
    sa.Enum(CryptoPairEnum, name=ENUM_NAME).create(op.get_bind())
    
    op.add_column('transactions', sa.Column('crypto_pair', sa.Enum(CryptoPairEnum, name=ENUM_NAME), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'crypto_pair')

    op.execute(f"DROP TYPE IF EXISTS {ENUM_NAME}")
    # ### end Alembic commands ###
